export const ONCHAINKIT_API_KEY = process.env.NEXT_PUBLIC_ONCHAINKIT_API_KEY || 'pLDbKzLfwJHWRY_UpuPL1U2xxlCYLhBI';
export const ONCHAINKIT_PROJECT_ID = process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_ID || '4d13d20e-5733-4076-80e5-efb2f5dd95e0';
